### ISSUE TITLE
support symbolic links

### ISSUE THREAD

**Issue by thomasrebele** [HBPMedical/PostgresRAW#2]
Hello,

it seems that PostgresRaw has problems with paths that contain symbolic links

If I initialize PostgresRaw with directory /tmp/postgresraw as PGDATA, then everything works as expected.
```
$ bin/pg_ctl start -D /tmp/postgresraw -l /tmp/postgres.log
$ echo "select count(*) from allfacts;" | bin/psql -U tr db
 count 
-------
 99565
(1 row)
```

However, if I execute 
```
$ ln -s /tmp/postgresraw /tmp/postlink
$ bin/pg_ctl start -D /tmp/postlink -l /tmp/postgres.log
$ echo "select count(*) from allfacts;" | bin/psql -U tr db
 count 
-------
     0
(1 row)
```
then I get no results. Is this easy to fix? Otherwise it would be helpful to mention it in the Readme.

All the best,
Thomas

**Comment by thomasrebele** [comment]
PS: some log messages why access to files registered in snoop.conf fails, would be nice, too

**Comment by amolma** [comment]
Dear Thomas,

There is indeed a problem when using softlink to the database.
Currently in order to locate the the snoop.conf file we use
current working directory and the PGDATA global variable given by the user as the -D argument.
Thus, the problem created is that when a soft link is created the concatenation of the strings creates a non existing location.

We can either add this as part of our documentation or make a more comprehensive analysis of the setup and derive the location of snoop.conf more efficiently.

Sincerely,
Matt

**Comment by thomasrebele** [comment]
Dear Matt,

thanks for your reply! I think I solved the problem by putting the database in a path that does not contain symbolic links :) It would be nice to mention it in the documentation, for the other users.

All the best,
Thomas

**Comment by amolma** [comment]
Of course :)

Thank you for noticing! I added a warning in the ReadMe file.

Sincerely,
Matt
